# Generated by Django 4.1.5 on 2023-01-18 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailEnviar',
            new_name='Emails',
        ),
    ]
